// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public interface avgWeatherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.avgWeatherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool succes = 1;</code>
   * @return The succes.
   */
  boolean getSucces();

  /**
   * <code>string weather = 2;</code>
   * @return The weather.
   */
  java.lang.String getWeather();
  /**
   * <code>string weather = 2;</code>
   * @return The bytes for weather.
   */
  com.google.protobuf.ByteString
      getWeatherBytes();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
