// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public interface avgWeatherRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.avgWeatherRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string period = 1;</code>
   * @return The period.
   */
  java.lang.String getPeriod();
  /**
   * <code>string period = 1;</code>
   * @return The bytes for period.
   */
  com.google.protobuf.ByteString
      getPeriodBytes();

  /**
   * <code>string location = 2;</code>
   * @return The location.
   */
  java.lang.String getLocation();
  /**
   * <code>string location = 2;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();
}
