// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public interface WeatherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.WeatherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string weather = 2;</code>
   * @return The weather.
   */
  java.lang.String getWeather();
  /**
   * <code>string weather = 2;</code>
   * @return The bytes for weather.
   */
  com.google.protobuf.ByteString
      getWeatherBytes();

  /**
   * <code>string error_message = 3;</code>
   * @return The errorMessage.
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 3;</code>
   * @return The bytes for errorMessage.
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
