// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public final class Weather {
  private Weather() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_avgWeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_avgWeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_avgWeatherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_avgWeatherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\010be.cloud\"0\n\016WeatherRequ" +
      "est\022\014\n\004date\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\"5\n\021a" +
      "vgWeatherRequest\022\016\n\006period\030\001 \001(\t\022\020\n\010loca" +
      "tion\030\002 \001(\t\"J\n\017WeatherResponse\022\017\n\007success" +
      "\030\001 \001(\010\022\017\n\007weather\030\002 \001(\t\022\025\n\rerror_message" +
      "\030\003 \001(\t\"L\n\022avgWeatherResponse\022\016\n\006succes\030\001" +
      " \001(\010\022\017\n\007weather\030\002 \001(\t\022\025\n\rerror_message\030\003" +
      " \001(\t2\237\001\n\016WeatherService\022A\n\ngetWeather\022\030." +
      "be.cloud.WeatherRequest\032\031.be.cloud.Weath" +
      "erResponse\022J\n\rgetAvgWeather\022\033.be.cloud.a" +
      "vgWeatherRequest\032\034.be.cloud.avgWeatherRe" +
      "sponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_cloud_WeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_cloud_WeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherRequest_descriptor,
        new java.lang.String[] { "Date", "Location", });
    internal_static_be_cloud_avgWeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_cloud_avgWeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_avgWeatherRequest_descriptor,
        new java.lang.String[] { "Period", "Location", });
    internal_static_be_cloud_WeatherResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_be_cloud_WeatherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherResponse_descriptor,
        new java.lang.String[] { "Success", "Weather", "ErrorMessage", });
    internal_static_be_cloud_avgWeatherResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_be_cloud_avgWeatherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_avgWeatherResponse_descriptor,
        new java.lang.String[] { "Succes", "Weather", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
