// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public interface WeatherResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:be.cloud.WeatherResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string Temp = 1;</code>
   * @return The temp.
   */
  java.lang.String getTemp();
  /**
   * <code>string Temp = 1;</code>
   * @return The bytes for temp.
   */
  com.google.protobuf.ByteString
      getTempBytes();

  /**
   * <code>string neerslag = 2;</code>
   * @return The neerslag.
   */
  java.lang.String getNeerslag();
  /**
   * <code>string neerslag = 2;</code>
   * @return The bytes for neerslag.
   */
  com.google.protobuf.ByteString
      getNeerslagBytes();

  /**
   * <code>double windspeed = 3;</code>
   * @return The windspeed.
   */
  double getWindspeed();
}
