// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

public final class Weather {
  private Weather() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_be_cloud_WeatherResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_be_cloud_WeatherResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rweather.proto\022\010be.cloud\"0\n\016WeatherRequ" +
      "est\022\014\n\004date\030\001 \001(\t\022\020\n\010location\030\002 \001(\t\"D\n\017W" +
      "eatherResponse\022\014\n\004Temp\030\001 \001(\t\022\020\n\010neerslag" +
      "\030\002 \001(\t\022\021\n\twindspeed\030\003 \001(\0012S\n\016WeatherServ" +
      "ice\022A\n\ngetWeather\022\030.be.cloud.WeatherRequ" +
      "est\032\031.be.cloud.WeatherResponseB\002P\001b\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_be_cloud_WeatherRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_be_cloud_WeatherRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherRequest_descriptor,
        new java.lang.String[] { "Date", "Location", });
    internal_static_be_cloud_WeatherResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_be_cloud_WeatherResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_be_cloud_WeatherResponse_descriptor,
        new java.lang.String[] { "Temp", "Neerslag", "Windspeed", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
