// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: weather.proto

package be.cloud;

/**
 * Protobuf type {@code be.cloud.WeatherResponse}
 */
public final class WeatherResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:be.cloud.WeatherResponse)
    WeatherResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use WeatherResponse.newBuilder() to construct.
  private WeatherResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private WeatherResponse() {
    temp_ = "";
    neerslag_ = "";
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new WeatherResponse();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return be.cloud.Weather.internal_static_be_cloud_WeatherResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return be.cloud.Weather.internal_static_be_cloud_WeatherResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            be.cloud.WeatherResponse.class, be.cloud.WeatherResponse.Builder.class);
  }

  public static final int TEMP_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object temp_ = "";
  /**
   * <code>string Temp = 1;</code>
   * @return The temp.
   */
  @java.lang.Override
  public java.lang.String getTemp() {
    java.lang.Object ref = temp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      temp_ = s;
      return s;
    }
  }
  /**
   * <code>string Temp = 1;</code>
   * @return The bytes for temp.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTempBytes() {
    java.lang.Object ref = temp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      temp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NEERSLAG_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object neerslag_ = "";
  /**
   * <code>string neerslag = 2;</code>
   * @return The neerslag.
   */
  @java.lang.Override
  public java.lang.String getNeerslag() {
    java.lang.Object ref = neerslag_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      neerslag_ = s;
      return s;
    }
  }
  /**
   * <code>string neerslag = 2;</code>
   * @return The bytes for neerslag.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNeerslagBytes() {
    java.lang.Object ref = neerslag_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      neerslag_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WINDSPEED_FIELD_NUMBER = 3;
  private double windspeed_ = 0D;
  /**
   * <code>double windspeed = 3;</code>
   * @return The windspeed.
   */
  @java.lang.Override
  public double getWindspeed() {
    return windspeed_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(temp_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, temp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(neerslag_)) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, neerslag_);
    }
    if (java.lang.Double.doubleToRawLongBits(windspeed_) != 0) {
      output.writeDouble(3, windspeed_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(temp_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, temp_);
    }
    if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(neerslag_)) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, neerslag_);
    }
    if (java.lang.Double.doubleToRawLongBits(windspeed_) != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(3, windspeed_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof be.cloud.WeatherResponse)) {
      return super.equals(obj);
    }
    be.cloud.WeatherResponse other = (be.cloud.WeatherResponse) obj;

    if (!getTemp()
        .equals(other.getTemp())) return false;
    if (!getNeerslag()
        .equals(other.getNeerslag())) return false;
    if (java.lang.Double.doubleToLongBits(getWindspeed())
        != java.lang.Double.doubleToLongBits(
            other.getWindspeed())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TEMP_FIELD_NUMBER;
    hash = (53 * hash) + getTemp().hashCode();
    hash = (37 * hash) + NEERSLAG_FIELD_NUMBER;
    hash = (53 * hash) + getNeerslag().hashCode();
    hash = (37 * hash) + WINDSPEED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getWindspeed()));
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static be.cloud.WeatherResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.WeatherResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.WeatherResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.WeatherResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.WeatherResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static be.cloud.WeatherResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static be.cloud.WeatherResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.WeatherResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static be.cloud.WeatherResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static be.cloud.WeatherResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static be.cloud.WeatherResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static be.cloud.WeatherResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(be.cloud.WeatherResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code be.cloud.WeatherResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:be.cloud.WeatherResponse)
      be.cloud.WeatherResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return be.cloud.Weather.internal_static_be_cloud_WeatherResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return be.cloud.Weather.internal_static_be_cloud_WeatherResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              be.cloud.WeatherResponse.class, be.cloud.WeatherResponse.Builder.class);
    }

    // Construct using be.cloud.WeatherResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      temp_ = "";
      neerslag_ = "";
      windspeed_ = 0D;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return be.cloud.Weather.internal_static_be_cloud_WeatherResponse_descriptor;
    }

    @java.lang.Override
    public be.cloud.WeatherResponse getDefaultInstanceForType() {
      return be.cloud.WeatherResponse.getDefaultInstance();
    }

    @java.lang.Override
    public be.cloud.WeatherResponse build() {
      be.cloud.WeatherResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public be.cloud.WeatherResponse buildPartial() {
      be.cloud.WeatherResponse result = new be.cloud.WeatherResponse(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(be.cloud.WeatherResponse result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.temp_ = temp_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.neerslag_ = neerslag_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.windspeed_ = windspeed_;
      }
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof be.cloud.WeatherResponse) {
        return mergeFrom((be.cloud.WeatherResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(be.cloud.WeatherResponse other) {
      if (other == be.cloud.WeatherResponse.getDefaultInstance()) return this;
      if (!other.getTemp().isEmpty()) {
        temp_ = other.temp_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getNeerslag().isEmpty()) {
        neerslag_ = other.neerslag_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.getWindspeed() != 0D) {
        setWindspeed(other.getWindspeed());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              temp_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              neerslag_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 25: {
              windspeed_ = input.readDouble();
              bitField0_ |= 0x00000004;
              break;
            } // case 25
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object temp_ = "";
    /**
     * <code>string Temp = 1;</code>
     * @return The temp.
     */
    public java.lang.String getTemp() {
      java.lang.Object ref = temp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        temp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string Temp = 1;</code>
     * @return The bytes for temp.
     */
    public com.google.protobuf.ByteString
        getTempBytes() {
      java.lang.Object ref = temp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        temp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string Temp = 1;</code>
     * @param value The temp to set.
     * @return This builder for chaining.
     */
    public Builder setTemp(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      temp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string Temp = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemp() {
      temp_ = getDefaultInstance().getTemp();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string Temp = 1;</code>
     * @param value The bytes for temp to set.
     * @return This builder for chaining.
     */
    public Builder setTempBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      temp_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object neerslag_ = "";
    /**
     * <code>string neerslag = 2;</code>
     * @return The neerslag.
     */
    public java.lang.String getNeerslag() {
      java.lang.Object ref = neerslag_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        neerslag_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string neerslag = 2;</code>
     * @return The bytes for neerslag.
     */
    public com.google.protobuf.ByteString
        getNeerslagBytes() {
      java.lang.Object ref = neerslag_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        neerslag_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string neerslag = 2;</code>
     * @param value The neerslag to set.
     * @return This builder for chaining.
     */
    public Builder setNeerslag(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      neerslag_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string neerslag = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearNeerslag() {
      neerslag_ = getDefaultInstance().getNeerslag();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string neerslag = 2;</code>
     * @param value The bytes for neerslag to set.
     * @return This builder for chaining.
     */
    public Builder setNeerslagBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      neerslag_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private double windspeed_ ;
    /**
     * <code>double windspeed = 3;</code>
     * @return The windspeed.
     */
    @java.lang.Override
    public double getWindspeed() {
      return windspeed_;
    }
    /**
     * <code>double windspeed = 3;</code>
     * @param value The windspeed to set.
     * @return This builder for chaining.
     */
    public Builder setWindspeed(double value) {

      windspeed_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>double windspeed = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWindspeed() {
      bitField0_ = (bitField0_ & ~0x00000004);
      windspeed_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:be.cloud.WeatherResponse)
  }

  // @@protoc_insertion_point(class_scope:be.cloud.WeatherResponse)
  private static final be.cloud.WeatherResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new be.cloud.WeatherResponse();
  }

  public static be.cloud.WeatherResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<WeatherResponse>
      PARSER = new com.google.protobuf.AbstractParser<WeatherResponse>() {
    @java.lang.Override
    public WeatherResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<WeatherResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<WeatherResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public be.cloud.WeatherResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

