# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Weather_pb2 as Weather__pb2


class WeatherServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getWeather = channel.unary_unary(
                '/be.cloud.WeatherService/getWeather',
                request_serializer=Weather__pb2.WeatherRequest.SerializeToString,
                response_deserializer=Weather__pb2.WeatherResponse.FromString,
                )
        self.getAvgWeather = channel.unary_unary(
                '/be.cloud.WeatherService/getAvgWeather',
                request_serializer=Weather__pb2.avgWeatherRequest.SerializeToString,
                response_deserializer=Weather__pb2.avgWeatherResponse.FromString,
                )


class WeatherServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def getWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getAvgWeather(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.getWeather,
                    request_deserializer=Weather__pb2.WeatherRequest.FromString,
                    response_serializer=Weather__pb2.WeatherResponse.SerializeToString,
            ),
            'getAvgWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.getAvgWeather,
                    request_deserializer=Weather__pb2.avgWeatherRequest.FromString,
                    response_serializer=Weather__pb2.avgWeatherResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'be.cloud.WeatherService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeatherService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def getWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/be.cloud.WeatherService/getWeather',
            Weather__pb2.WeatherRequest.SerializeToString,
            Weather__pb2.WeatherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def getAvgWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/be.cloud.WeatherService/getAvgWeather',
            Weather__pb2.avgWeatherRequest.SerializeToString,
            Weather__pb2.avgWeatherResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
