version: '3.4'

services:
  feestbegeleiding:
    image: feestbegeleiding
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 4000:4000
